### ISSUE TITLE
Related stories are broken in IE 11

### ISSUE THREAD

**Issue by jonathanstegall** [MinnPost/minnpost-largo#134]
It's a small fix though:

```css
.a-related-list {
flex: 1 0 100%;
}
```
